### PR TITLE
Change RedDotRubyConf URL to current CFP

### PR DESCRIPTION
**Pull request by hanmd82**
Link to CFP URL for RDRC 2017, instead of conference link from 2016

### CODE REVIEW

**Comment by hanmd82** [comment]
The htmlproofer error is not caused by this commit - it is actually caused by a URL that takes a while to load (probably due to a redirect - the link is valid)

**Comment by hanmd82** [comment]
closing this PR as the conf website has been updated 👍

**Comment by jonallured** [comment]
thanks @hanmd82 - btw: this was totally on my list for today, sorry about the delay! ;)

**Comment by hanmd82** [comment]
Thanks @jonallured for putting it up in the first place 👍

**Pull request closed without merging**
