### PR TITLE
Submit info for 2018 RubyHACK conference

### PR DESCRIPTION
**Pull request by aamax**

### CODE REVIEW

**Comment by aamax** [comment]
On my last PR, there were a few issues brought up by Travis etc. that were from other developers... and already in master.   Not sure what I can/should do about them if they choke on me again.  I'll wait and see how it goes this time though.

**Comment by aamax** [comment]
All of these failures are from commits already in master... none are my code.   How do I resolve this?

**Comment by jonallured** [comment]
Yeah, this is weird, let's see if we can get things sorted out. What I did was clone your fork on my machine and looked at where things stood:

screen shot 2017-10-12 at 9 56 43 pm

So we see that there's a merge commit there that we don't want. My approach was to check back to where upstream/master should be and start a new branch:

```
jon@colossus:~/code/aamax-rc(omglol)% git checkout 20d0855
jon@colossus:~/code/aamax-rc(omglol)% git checkout -b omglol
```

So then things look like this:

screen shot 2017-10-12 at 9 57 15 pm

Now we want to cherry pick that commit from master to get your changes in line with upstream/master:

```
jon@colossus:~/code/aamax-rc(omglol)% git cherry-pick 85b7327
```

And now we're in good shape:

screen shot 2017-10-12 at 9 58 32 pm

So, my thought would then be to fix your master like this:

```
jon@colossus:~/code/aamax-rc(master)% git checkout master
jon@colossus:~/code/aamax-rc(master)% git reset --hard omglol
```

Which gives you this:

screen shot 2017-10-12 at 10 05 50 pm

And then you can force push your master:

```
jon@colossus:~/code/aamax-rc(master)% git push -f
```

Which should do two things:

* get your fork back in good shape with upstream
* automatically update #193 

And I think that's it - see, isn't git easy! 😝

**Comment by aamax** [comment]
Ok, followed your suggestions and did the force push. 

I've never used cherry pick - will look at that closer and have never done a reset with specifying a branch name...   I have kept my git usage to simple, non-invasive stuff over time so I don't get in trouble :)   thanks for the tips

**Comment by jonallured** [comment]
Yay, thanks for the PR and glad that helped! ❤️

**Pull request merged**
