### PR TITLE
Add wroclove.rb cfp closing date

### PR DESCRIPTION
**Pull request by piotrj**
Apparently it is closing on January 31.

### CODE REVIEW

**Comment by ChrisGuzman** [comment]
The [CFP site](http://cfp-wrocloverb.herokuapp.com/authentications) says it closes January 12th

**Comment by piotrj** [comment]
@ChrisGuzman interesting, you are right - it says that before you log in. But once you're in it says 31 January 
screen shot 2017-01-06 at 20 52 35.

I guess we have to contact organizers.

**Comment by ChrisGuzman** [comment]
It looks like they close Jan 31 https://twitter.com/wrocloverb/status/817481479655686144

**Comment by jonallured** [comment]
Thanks @piotrj for the PR and thanks @ChrisGuzman for helping to clarify! ❤️ ❤️ ❤️

**Pull request merged**
