### PR TITLE
Update with EuRuKo 2020; Ruby AU 2020

### PR DESCRIPTION
**Pull request by FloorD**

### CODE REVIEW

**Comment by jonallured** [comment]
Oh sorry, this is just failing because the title of the commit is lowercase (not the GitHub issue). Thanks!

**Comment by jonallured** [comment]
Hey I think this one needs a rebase and then just an update on the commit message to pass CI.

**Comment by Morozzzko** [comment]
@jonallured I'm thinking the Danger rule should emit a warning instead of an error, what do you think?

Commit messages don't seem to matter much if your merge strategy is `rebase and merge`, or `squash and merge` – we'll get the chance to rename the commit however we please.

Or we could update the error message to avoid situations like this one.

I'd love to see the conferences, but this Danger thingie seems more like an obstacle.

**Comment by Morozzzko** [comment]
@FloorD do you think you could fix the conflicts and the commit message? I want to see EuRuKo on the website, but this delay is quite unfortunate

**Comment by jonallured** [comment]
I ended up just getting this in there with a commit on master, thanks all!

**Pull request closed without merging**
