### PR TITLE
Brighton 2024 CFP

### PR DESCRIPTION
**Pull request by andycroll**

### CODE REVIEW

**Review by marcoroth — APPROVED** [review]
Looks good to me!

I was wondering if we should/could add a `cfp_link` key as well, so people can easily get to the CFP page.

Because I just had a quick look at https://brightonruby.com and couldn't find a link to the CFP platform. But there is also a good chance that I was too quick and that it's coming 🙈

**Comment by andycroll** [comment]
I _literally_ just tried to add that... then noticed we don't have that.

**Comment by marcoroth** [comment]
Going to add it in another pull request, but we can merge this as-is 👍🏼

**Comment by marcoroth** [comment]
Just put up #572 to address this

**Pull request merged**
