### PR TITLE
Added Ruby devroom at FOSDEM 2017

### PR DESCRIPTION
**Pull request by heliocola**

### CODE REVIEW

**Comment by jonallured** [comment]
Hi @heliocola, turns out that GitHub changed something about comment parsing and that broke Danger, which is the reason for @TheRCBot's garbled message. I have fixed this on master by upgrading Danger to 4.x, so could you please rebase on top of that and push a new commit to this PR? While you're at it, please also remove the period at the end of your commit message.

Thanks! ❤️ ❤️ ❤️

**Comment by heliocola** [comment]
@jonallured did you mean the period in the PR title, correct?
That was removed and I merged your latest into my fork#master branch.
Please let me know if you need anything else.

**Comment by jonallured** [comment]
Hey @heliocola, what I was actually hoping for was a rebase so that there's no merge commit. And the period at the end of the commit message is what I was referring to, not the PR title. I've got Danger configured to fail when the commit message doesn't match these rules:

https://github.com/jonallured/danger-commit_lint#usage

**Comment by heliocola** [comment]
@jonallured I will close this one and submit a new one.

**Pull request closed without merging**
