### PR TITLE
Fix ordering issue for June 2023 conferences

### PR DESCRIPTION
**Pull request by swanson**
Rails SaaS 2023 is happening before Blue Ridge Ruby 2023

### CODE REVIEW

**Comment by marcoroth** [comment]
You were faster than me 😅 



I tried a different approach though, but I've been waiting for Ruby 2.5.3 to install so I could test it 🙃  

Screenshot 2023-02-03 at 15 02 41

**Comment by jonallured** [comment]
LOL you mean hard-coding an order isn't the best approach 😝 who even knows how dates work??

**Comment by marcoroth** [comment]
🙈 

Would you be interested in such a change (and eventually a Ruby upgrade as well)?

**Comment by swanson** [comment]
> LOL you mean hard-coding an order isn't the best approach 😝 who even knows how dates work??

I think it's actually fine to hard-code! Especially since you could have overlapping dates, etc. Keep it boring :)

**Pull request merged**
