### PR TITLE
Update RubyKaigi, which is changing dates

### PR DESCRIPTION
**Pull request by noahgibbs**
RubyKaigi 2017 is over. But RubyKaigi 2018 is (unexpectedly) changing what time of year they have it starting in 2018. Doesn't look like the CfP is open yet.

### CODE REVIEW

**Comment by jonallured** [comment]
Cool, rather than simply removing the 2017 event, would you mind moving it to the past.yaml file? Thanks!

**Comment by noahgibbs** [comment]
Ah, sorry! Fixed.

**Comment by noahgibbs** [comment]
Merged w/ latest master.

**Comment by jonallured** [comment]
Oops, I was cherry-picking and fixing this up locally while you were merging, haha. Oh well, thank you very much for this PR and I've got this deployed out to production. ❤️

**Comment by noahgibbs** [comment]
No problem! Just happy to see the site updating :-)

**Pull request closed without merging**
