### PR TITLE
Add Isle of Ruby and JRubyConf UK

### PR DESCRIPTION
**Pull request by myabc**
(CFP and Registration not yet available)

/ @wordgraphy @sardaukar

### CODE REVIEW

**Comment by sardaukar** [comment]
So we're totally set on the date?

**Comment by jonallured** [comment]
Sounds like there's still some debate on the details - let me know when this is ready to merge! 😄

**Comment by sardaukar** [comment]
@jonallured my mistake, good to go!

**Comment by jonallured** [comment]
Thanks for the PR - I just deployed the site!! :D

**Pull request closed without merging**
