### PR TITLE
Add RubyHACK 2017 conference to current list

### PR DESCRIPTION
**Pull request by aamax**

### CODE REVIEW

**Comment by aamax** [comment]
I'm just learning how to submit PR for your site.  Gonna reorder the placement of my conf and fix the commit name...

**Comment by jonallured** [comment]
No problem @aamax and if you need help with something, let me know - happy to help people that are learning!!! :D

**Comment by aamax** [comment]
I made a PR and it said 2 errors.  One was "Please start subject with capital letter"... I don't see any subject in the yaml so I figure that means the commit comment....  I don't know of any other errors so I'll try again with that (unless you have other feedback for me!).   thanks

**Comment by jonallured** [comment]
Yeah, that error is triggered when the commit subject lines doesn't start with a capital letter. You can either open a new PR or just push your updated commit to your branch and GitHub should update this PR automagically.

**Comment by jonallured** [comment]
* force push, that is...

**Comment by aamax** [comment]
Ok.  I was trying to rebase and squash and was heading down the rabbit hole.  I'll make a new PR.  thanks

**Comment by jonallured** [comment]
Ugh, git can be such a pain in the ass sometimes...

In the spirit of sharing, here's what I would have done:

```
$ git commit --amend
# capitalize first character
$ git push --force
# this pr is based off of your fork's `master` branch, so that would probably have been enough
```

But a new PR is totally cool too - just trying to be helpful! ❤️  ❤️  ❤️

**Comment by aamax** [comment]
that's what I started doing.  I'm not too unfamiliar with git, just not with doing PRs etc.  Trying not to pollute the repo etc.   Thanks for the tips.

**Pull request closed without merging**
