### PR TITLE
CfP for Ruby on Ice is open.

### PR DESCRIPTION
**Pull request by bascht**
As of today, we're open for proposals. 😃

### CODE REVIEW

**Comment by bascht** [comment]
…well, I can fix one of those two errors. 🤔

**Comment by jonallured** [comment]
Yeah, ignore the build errors about those links - I can't figure out why Travis is failing to reach these sites that come up fine for me. :(

**Comment by bascht** [comment]
@jonallured No worries. The `.` is fixed. 

On a slightly different note: HOW DO YOU MANAGE TO REACT TO PRs SO QUICKLY? 😸

**Comment by jonallured** [comment]
You just got lucky - poor @gato-omega had to wait _days_ on #173!! 😝

**Pull request merged**
