### PR TITLE
Rubyday 2020 new date

### PR DESCRIPTION
**Pull request by giuliatosato**

### CODE REVIEW

**Comment by jonallured** [comment]
Hi @giuliatosato would you mind moving this event down the list so that it appears in the right order? Thanks!

**Comment by giuliatosato** [comment]
hi @jonallured, all fixed! thank you

**Comment by adarsh** [comment]
Seems stale. Close without merging or merge for historical record?

**Comment by marcoroth** [comment]
I'd vote for merging to have the historical record

**Comment by marcoroth** [comment]
Okay, after looking at https://2020.rubyday.it I think the information in this PR is actually right. Should we just resolve the conflicts and merged it to have the historical record?

**Comment by marcoroth** [comment]
Actually, this was already added in https://github.com/ruby-conferences/ruby-conferences.github.io/pull/379 and the correct dates are also on `master`. So I think we can just close this.

**Pull request closed without merging**
