### PR TITLE
BalticRuby: Dates for 2025 - June 12-14, 2024

### PR DESCRIPTION
**Pull request by Sergyenko**
there we go 🤗

### CODE REVIEW

**Comment by Sergyenko** [comment]
Hi folks, I'm not sure what went wrong with the checks :( 

Let me know how to fix it

**Comment by marcoroth** [comment]
Hey, @Sergyenko, thank you!

It's "complaining" now because it expects the conferences to be in order. Since the date changed from `2025-12-31` to `2025-06-12` it's now not in the "right" position anymore. 

If you move it up in-between Helvetic Ruby 2025 and Brighton Ruby 2025 it should be fine again.

**Comment by Sergyenko** [comment]
Gotcha! Fixed it just now!

**Review by marcoroth — APPROVED** [review]
Awesome, thank you so much! 🙌🏼

**Pull request merged**
