### PR TITLE
Add RubyHACK 2017

### PR DESCRIPTION
**Pull request by aamax**

### CODE REVIEW

**Comment by aamax** [comment]
I looked at the failure and don't see why at this point.  Help?

HTML-Proofer finished successfully.
Bonus keys: ["cfp-phrase"]
{"name"=>"RubyHACK", "location"=>"Salt Lake City, Utah", "dates"=>"April 20-21, 2017", "url"=>"http://rubyhack.com/", "twitter"=>"utrubyhack", "reg_phrase"=>"Registration is open", "cfp-phrase"=>"CFP open"}
Danger has failed this build. 
Found 1 error.
The command "bundle exec danger" exited with 1.
Done. Your build exited with 1.

**Comment by jonallured** [comment]
Ok, I think I see what's going on - looks like you used `cfp-phrase`, not `cfp_phrase`. I think fixing that should get you a green build on Travis and a merge from me! 😄

**Comment by aamax** [comment]
Thanks for your help with this!  👍

**Comment by jonallured** [comment]
Thanks for the PR - I just deployed the site!! :D

**Pull request merged**
