### PR TITLE
Add Balkan Ruby, Ruby Dev Summit, and upgrade Ruby

### PR DESCRIPTION
**Pull request by ivoanjo**

### CODE REVIEW

**Comment by jonallured** [comment]
Let's split this up - if you rebase out the 2.4.2 upgrade, then I can merge the events you've added. I can deal with the Ruby upgrade myself separately.

**Comment by ivoanjo** [comment]
@jonallured done :white_check_mark:

**Comment by jonallured** [comment]
Oops, looks like there are still some left-overs in https://github.com/ruby-conferences/ruby-conferences.github.io/pull/186/commits/658e91bb47f73117802a8352ea334fdcc1132d72

**Comment by ivoanjo** [comment]
Indeed, drinking :cocktail: and git'ing is not a good combo :scream: 
Third time's the charm, sorry for the confusion!

**Comment by jonallured** [comment]
Awesome, thanks so much for your help!!

**Pull request merged**
