### PR TITLE
Add ROSS conf Amsterdam

### PR DESCRIPTION
**Pull request by FloorD**

### CODE REVIEW

**Comment by jonallured** [comment]
Cool - my only feedback is that you probably want "Registration closes" for the `reg_phrase` so that it ends up reading like this:

> Registration closes May 8, 2018

With that update I'll happily merge! 😄

**Comment by FloorD** [comment]
@jonallured added :)

**Comment by jonallured** [comment]
Oops, this is what I was trying to suggest:

```yaml
- name: ROSS conf Amsterdam
  location: Amsterdam, the Netherlands
  dates: "May 11-12, 2018"
  url: https://rossconfams.eventbrite.co.uk
  twitter: rossconf
  reg_phrase: "Registration closes"
  reg_date: "May 8, 2018"
```

The `reg_phrase` and `reg_date` and joined when both are present:

https://github.com/ruby-conferences/ruby-conferences.github.io/blob/4f5463347a33033d75952da42384aa60975e8f71/js/behavior.js#L18

Sorry for the confusion!!

**Comment by FloorD** [comment]
@jonallured we're getting there ;)

**Comment by jonallured** [comment]
Thanks for the PR - I just deployed the site!! :D

**Pull request merged**
