### PR TITLE
Move RubyConfPT and KeepRubyWeird to past

### PR DESCRIPTION
**Pull request by benoittgt**

### CODE REVIEW

**Comment by jonallured** [comment]
Hey @benoittgt, thanks for the PR! I see that [the first build][first] failed with a couple 403s, but then I just tried those links in my browser and they resolved just fine, so I'm not sure what's going on there. :\

[first]: https://travis-ci.org/ruby-conferences/ruby-conferences.github.io/builds/172545262

The [the second build][second] also failed and that error I do understand - when you move events from the current list to the past list you have to remove the keys that don't belong. In this case that's the `reg_phrase` keys.

[second]: https://travis-ci.org/ruby-conferences/ruby-conferences.github.io/builds/172547034

What I'm thinking is that you remove 97294bc from the PR and then if you can amend 63dd51d to remove those keys, then Travis should pass and I'll merge in your commits.

Thanks again! ❤️  ❤️  ❤️

**Comment by benoittgt** [comment]
Thanks @jonallured for feedbacks. I've update the commit.

**Comment by jonallured** [comment]
Grrr, it looks like those URLs 403ed again on Travis. I don't understand what's going on there, but I'm going to merge your commits and deploy the site.

**Comment by jonallured** [comment]
Lol, then this job passes: https://travis-ci.org/ruby-conferences/ruby-conferences.github.io/builds/172649190

SIGH

**Comment by benoittgt** [comment]
Ahah. Thanks @jonallured

**Pull request merged**
