### PR TITLE
Add RailsConf 2021 Event Videos 🍿

### PR DESCRIPTION
**Pull request by artkirienko**
https://www.youtube.com/playlist?list=PLbHJudTY1K0c8N1-PPyiQxlHNzJIzyJv6

RailsConf-2021-YouTube

### CODE REVIEW

**Review by LegaKh — APPROVED** [review]

**Review by filipewl — APPROVED** [review]

**Review by ST-YuryOtcheski — APPROVED** [review]

**Review by navigator3228 — APPROVED** [review]

**Review by vladzaets — APPROVED** [review]

**Review by Neodelf — APPROVED** [review]
👍 Nice job!
❤️ Thank you for your contribution!

**Review by isavinof — APPROVED** [review]

**Review by vvalgis — APPROVED** [review]

**Review by swember — APPROVED** [review]

**Review by IvanTakarlikov-st — APPROVED** [review]

**Review by Evshved — APPROVED** [review]

**Review by IlyasValiullov — APPROVED** [review]

**Review by HooFoo — APPROVED** [review]

**Review by Spitsman — APPROVED** [review]

**Review by ilukashin — APPROVED** [review]

**Review by fidalgo — APPROVED** [review]
🚢 🇮🇹

**Review by SeTeM — APPROVED** [review]

**Review by cylon-v — APPROVED** [review]

**Review by LubaLimon — APPROVED** [review]

**Review by msokolov93 — APPROVED** [review]
all good

**Comment by jonallured** [comment]
LOL thanks for all the approval friends! 😝

**Pull request merged**
