### PR TITLE
Add Ruby devroom at FOSDEM 2024

### PR DESCRIPTION
**Pull request by heliocola**

### CODE REVIEW

**Comment by heliocola** [comment]
@jonallured : I've made the same typo in the CFP message here.
Ruby Devroom at FOSDEM was my first ever conference I spoke! 💟

**Review by marcoroth — APPROVED** [review]
Not sure what the others think because it's strictly speaking not a Ruby Conference, but I think this is as close as it gets, which is why I'd say 👍🏼

**Comment by heliocola** [comment]
@marcoroth : thanks for the comment. I agree it is not technically a Ruby Conference and I agree it is as close as it gets!
I submitted the PR given the events from 2015, 2016, and 2017 were added.

I've also first learned about the Ruby Devroom at FOSDEM on rubyconferences.org.
And that was my first ever conference that I was accepted as a speaker... so I have some attachment to it!

Anyway, FOSDEM is a free and noncomercial (ref: https://fosdem.org/2024/about/) conference with its own format, it is held in an university Campus, and some history, and some issues.

DISCLAIMER: I am not an organizer, and I've submitted a talk this year again! 💟

**Comment by marcoroth** [comment]
Awesome, thanks for the context @heliocola! 🙌🏼

**Pull request merged**
