### PR TITLE
Add Kiwi Ruby

### PR DESCRIPTION
**Pull request by mermop**
:sparkles: 

(we are officially announcing this in 6 and a half hours but I'm scheduling everything now so figure it can't hurt to make this PR a little early)

### CODE REVIEW

**Comment by mermop** [comment]
I'm confused about what the bot is upset about sorry

**Comment by jonallured** [comment]
@mermop sorry - it's the commit messages. I can see why this is confusing and I have an issue for improving the feedback, but I haven't quite got to it yet.

https://github.com/jonallured/danger-commit_lint/issues/10

If you just amend those messages to start with a capital letter, then I'll merge and deploy the site.

Sorry for the trouble!

**Comment by mermop** [comment]
That's fixed now @jonallured, thanks

**Comment by jonallured** [comment]
@mermop no problem on the broken links, sometimes htmlproofer is a liar about these things. 😄

**Pull request merged**
