### PR TITLE
Update RubyHACK info

### PR DESCRIPTION
**Pull request by aamax**

### CODE REVIEW

**Comment by aamax** [comment]
I changed the PR name to start with an Upper case letter but don't see how I can restart Travis...   can you help me with that?   Thanks...

**Comment by paneq** [comment]
@aamax why did you commit RubyMine settings?

**Comment by aamax** [comment]
So sorry.  Was confused and will fix it when I get to puter

**Comment by aamax** [comment]
Going to fix this PR and resubmit

**Pull request closed without merging**
