### PR TITLE
Add Rails Camp West 2023

### PR DESCRIPTION
**Pull request by marcoroth**
https://twitter.com/railscamp_USA/status/1620783962342985728

### CODE REVIEW

**Comment by geraldb** [comment]
@marcoroth  You are welcome to add the rails camp west over here <https://github.com/planetruby/conferences/blob/master/_data/conferences2023.yml> at planet ruby.   PS:  Since you look like adding many events I am happy to get you added as member / committer  (alas   over at Planet Ruby - for more on working together - see  <https://github.com/ruby-conferences/ruby-conferences.github.io/issues/409> ).

**Comment by CamiloGarciaLaRotta** [comment]
👋🏼 @marcoroth curious if you are planning to land your PR 🙃 @bobbilee19 (the organizer of Rails Camp West 2023) was hoping to get the event into ruby-conferences.github.io

**Comment by marcoroth** [comment]
Hey @CamiloGarciaLaRotta, I'm not able to merge the PR myself 🙈

**Comment by jonallured** [comment]
Merged!

**Pull request merged**
